---
title: "Lab2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lab2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SemesterProjectLabII)
```

```{r}
library(tibble)
simple_design <- tibble(group = rep(c(0,1), each=10),
                        DV = c(1,3,2,4,3,4,5,6,5,4,5,4,3,2,3,4,5,6,8,9))

knitr::kable(simple_design)

```

```{r}
library(ggplot2)

ggplot(simple_design, aes(x=group, y=DV))+
  geom_bar(stat = "summary", fun = "mean", position="dodge")+
  geom_point()
```

```{r}
t.test(DV~group,var.equal=TRUE,data=simple_design)
```

```{r}
lm(DV~group, data=simple_design)
```

```{r}
recall_design <- tibble(practice = rep(c(2,4,8), each=3),
                        subjects = 1:9,
                        recall = c(5,7,8,
                                   8,10,12,
                                   12,15,17))
knitr::kable(recall_design)
```
```{r}

ggplot(recall_design, aes(x=practice, y=recall))+
  geom_bar(stat = "summary", fun = "mean", position="dodge")+
  geom_point()+
  geom_smooth(method="lm", formula = y~x, se=FALSE)
```
```{r}
summary(lm(recall~practice, data=recall_design))
```

### question,,, 

would you use questionnaire scoring in an experiment as a categorical of either High or Low,,, or is more common to use as a continuous variable for multiple regression...? I am confused on when you have multiple IV's should you always convert one to categorical to get a better analysis?




